---
title: "Simple document"
output: github_document
---

```{r, echo=FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

I'm an R Markdown document! 

#data import CSV

import data using reader package
```{r}
litters_df = read.csv("./data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)

head(litters_df)
tail(litters_df)
```

```{r, eval=FALSE}
view(litters_df)
skimr::skim(litters_df)
read_csv("./data/FAS_litters.csv", na = c(".","NA"), skip = 2)
```

"read_csv" functions

# need to read into excel spreadsheet
```{r}
read_excel("./data/mlb11.xlsx")
lr_words_df = 
  read_excel(
    "./data/LotR_Words.xlsx",
    range = "B2:D6"
  )
```

# read SAS dataset
```{r}
pulse_data = read_sas("./data/public_pulse_data.sas7bdat")
```

#data export
```{r}
write_csv(lr_words_df, file = "./data/lr_words_df.csv")
```

# data minipulation with dplyr
```{r}
options(tibble.print_min = 3)

litters_data = read_csv("./data/FAS_litters.csv",
  col_types = "ccddiiii")
litters_data = janitor::clean_names(litters_data)

pups_data = read_csv("./data/FAS_pups.csv",
  col_types = "ciiiii")
pups_data = janitor::clean_names(pups_data)
```

# select function
```{r}
#select the variables you want:
select(litters_data, group, litter_number, gd0_weight, pups_born_alive)

#specify a range of columns to keep
select(litters_data,group:gd_of_birth)

#specify columns you’d like to remove:
select(litters_data, -pups_survive, -litter_number)

#You can rename variables as part of this process (only have two columns in the new dataset)
select(litters_data, GROUP = group, LiTtEr_NuMbEr = litter_number)

#starts_with(),ends_with()
select(litters_data, starts_with("gd"))

# everything(), handy for reorganizing columns without discarding anything
select(litters_data, litter_number, pups_survive, everything())
#relocate does a similar thing (and is sort of like rename in that it’s handy but not critical):
relocate(litters_data, litter_number, pups_survive)
```
# rename instead of select
```{r}
#keep all the columns in the dataset just rename the two columns
rename(litters_data, GROUP = group, LiTtEr_NuMbEr = litter_number)

```

# filter 
```{r}
select(litters_data, gd_of_birth == 20)
pups_born_alive >= 2
pups_survive != 4

#"anything but"
!(pups_survive == 4)
!((pups_survive == 4) & (pups_born_alive >= 2))

group %in% c("Con7", "Con8")
group == "Con7" & gd_of_birth == 20

#omit missing observations. You can do this with filter, but I recommend using drop_na
#will remove any row with a missing value
drop_na(litters_data)
#will remove rows for which wt_increase is missing.
drop_na(litters_data, wt_increase) 

#Filter to include only pups with sex 1
filter(pups_data, sex == 1)

#Filter to include only pups with PD walk less than 11 and sex 2
filter(pups_data, sex == 2, pd_walk < 11)
```

#mutate
```{r}
mutate(litters_data,
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group)
)
```

#arrange
```{r}
#arrange the rows in your data according to the values in one or more columns
#use head(), print the first 10 rows of the dataset
head(arrange(litters_data, group, pups_born_alive), 10)
head(arrange(litters_data, desc(group), pups_born_alive), 10)

```

# %>%
```{r}
#not using %>%:
#option 1:
litters_data_raw = read_csv("./data/FAS_litters.csv",
  col_types = "ccddiiii")
litters_data_clean_names = janitor::clean_names(litters_data_raw)
litters_data_selected_cols = select(litters_data_clean_names, -pups_survive)
litters_data_with_vars = 
  mutate(
    litters_data_selected_cols, 
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group))
litters_data_with_vars_without_missing = 
  drop_na(litters_data_with_vars, wt_gain)
litters_data_with_vars_without_missing
#option 2:
litters_data_clean = 
  drop_na(
    mutate(
      select(
        janitor::clean_names(
          read_csv("./data/FAS_litters.csv", col_types = "ccddiiii")
          ), 
      -pups_survive
      ),
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)
    ),
  wt_gain
  )

litters_data_clean

#using %>%:
litters_data = 
  read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)) %>% 
  drop_na(wt_gain)

litters_data
```

# non-tidyverse function with piping
```{r}
litters_data %>%
  lm(wt_gain ~ pups_born_alive, data = .) %>%
  broom::tidy()
```


